git mv 17mai.jpg 17mai.jpg
git mv Akerselva.jpg akerselva.jpg
git mv Amber.jpg amber.jpg
git mv Asperud.jpg asperud.jpg
git mv Audur.jpg audur.jpg
git mv Bairnstock.jpg bairnstock.jpg
git mv Beethoven.jpg beethoven.jpg
git mv Berchta.jpg berchta.jpg
git mv Bergtatt.jpg bergtatt.jpg
git mv Bjornholt.jpg bjornholt.jpg
git mv Brenna.jpg brenna.jpg
git mv Brennamitts1.jpg brennamitts1.jpg
git mv Brennamitts2.jpg brennamitts2.jpg
git mv Brisingamen.jpg brisingamen.jpg
git mv Calixtus.jpg calixtus.jpg
git mv Crucified.jpg crucified.jpg
git mv Dandelion.jpg dandelion.jpg
git mv Dead.jpg dead.jpg
git mv Dragons.jpg dragons.jpg
git mv Draupnir.jpg draupnir.jpg
git mv Dyrtiden.jpg dyrtiden.jpg
git mv Eldbjorg.jpg eldbjorg.jpg
git mv Feldpost.jpg feldpost.jpg
git mv Garthenor1.jpg garthenor1.jpg
git mv Germans.jpg germans.jpg
git mv Gleipnir.jpg gleipnir.jpg
git mv Grandma.jpg grandma.jpg
git mv Grandpa.jpg grandpa.jpg
git mv Greteken.jpg greteken.jpg
git mv Grimnir.jpg grimnir.jpg
git mv Gunnhild.jpg gunnhild.jpg
git mv Gytha.jpg gytha.jpg
git mv Harry.jpg harry.jpg
git mv Hawaii.jpg hawaii.jpg
git mv Heidrun.jpg heidrun.jpg
git mv Heraldry.jpg heraldry.jpg
git mv Hildina.jpg hildina.jpg
git mv Huldra.jpg huldra.jpg
git mv Ingiridhbrown.jpg ingiridhbrown.jpg
git mv Ingiridhhandspun.jpg ingiridhhandspun.jpg
git mv Ingveld.jpg ingveld.jpg
git mv Jorunn.jpg jorunn.jpg
git mv Krigsfanger.jpg krigsfanger.jpg
git mv Kvennavagn.jpg kvennavagn.jpg
git mv Lanja.jpg lanja.jpg
git mv Lofsrud.jpg lofsrud.jpg
git mv Lofsrud1.jpg lofsrud1.jpg
git mv Longwinternight.jpg longwinternight.jpg
git mv Maridal.jpg maridal.jpg
git mv Mending.jpg mending.jpg
git mv Mortensrud.jpg mortensrud.jpg
git mv Myralokka.jpg myralokka.jpg
git mv Myrkwood.jpg myrkwood.jpg
git mv Norge.jpg norge.jpg
git mv Olsok.jpg olsok.jpg
git mv Oops.jpg oops.jpg
git mv Oslo1.jpg oslo1.jpg
git mv Oslo2.jpg oslo2.jpg
git mv Oslowide.jpg oslowide.jpg
git mv Ottesong1.jpg ottesong1.jpg
git mv Outgard.jpg outgard.jpg
git mv Pentecost.jpg pentecost.jpg
git mv Perfectionism.jpg perfectionism.jpg
git mv Redcrosssocks.jpg redcrosssocks.jpg
git mv Roskva.jpg roskva.jpg
git mv Saganight.jpg saganight.jpg
git mv Sankthans.jpg sankthans.jpg
git mv Skadi.jpg skadi.jpg
git mv Skole.jpg skole.jpg
git mv Solvarg.jpg solvarg.jpg
git mv Sommerdag.jpg sommerdag.jpg
git mv Sommerdag2.jpg sommerdag2.jpg
git mv Sommerdag3.jpg sommerdag3.jpg
git mv Steeltires.jpg steeltires.jpg
git mv Stenbraten.jpg stenbraten.jpg
git mv Stmartin.jpg stmartin.jpg
git mv Stricken.jpg stricken.jpg
git mv Sunflowerseeds.jpg sunflowerseeds.jpg
git mv Svanlaug.jpg svanlaug.jpg
git mv Svanlaugcloseup.jpg svanlaugcloseup.jpg
git mv Svanlaugwhite.jpg svanlaugwhite.jpg
git mv Tires.jpg tires.jpg
git mv Tora.jpg tora.jpg
git mv Troldhaugen.jpg troldhaugen.jpg
git mv Vitastjerna.jpg vitastjerna.jpg
git mv Vivja.jpg vivja.jpg
git mv Westfoldwheat.jpg westfoldwheat.jpg
git mv William2.jpg william2.jpg
